/* Generated By:JavaCC: Do not edit this line. PDDL21Parser.java */
package mt.uol.smi.attempto.aceview.pddl.sapa.parsing;

import java.util.*;

import org.apache.commons.lang.NotImplementedException;

import mt.uol.smi.attempto.aceview.pddl.ACEPlannerRunner;
import mt.uol.smi.attempto.aceview.pddl.IACEPlannerRunner;
import mt.uol.smi.attempto.aceview.pddl.model.ACEPlannerActionListModel;
import mt.uol.smi.attempto.aceview.pddl.model.ACEPlannerConditionModel;
import mt.uol.smi.attempto.aceview.pddl.model.ACEPlannerParameter;
import mt.uol.smi.attempto.aceview.pddl.model.ACEPlannerSnippet;
import mt.uol.smi.attempto.aceview.pddl.sapa.basic_ds.*;
import mt.uol.smi.attempto.aceview.pddl.sapa.parsing.PDDL21Parser.JJCalls;

public class ACEPDDLParser implements PDDL21ParserConstants {

	static private IACEPlannerRunner acepddl_runner;

	public ACEPDDLParser(IACEPlannerRunner runner) {
		acepddl_runner = runner;
	}

	/*******************************************************************/
	static final public ACEPlannerDomain parse_domain_pddl() {
		ACEPlannerDomain aDomain = new ACEPlannerDomain();
		String s;
		int i;
		List v = new ArrayList();
		s = DomainName();
		aDomain.setName(s);
		aDomain.setActions(acepddl_runner.getDomain().getActionListModel());
		return aDomain;
	}

	/******/
	static final public String DomainName() {
		String name = acepddl_runner.getDomain().getName();
		if (name != null)
			return name.toLowerCase();
		throw new Error("name is null function");
	}

	/*** Predicate instance declaration in the problem file ***/
	static final public Predicate ProbPred(ACEPlannerSnippet goalSnippet) {
		Token t;
		Predicate p = new Predicate();
		p.setName(goalSnippet.getSentence());
		p.addObj(goalSnippet.getAceSnippet().getAxiom(), 1);
		return p;
	}

	/*******/
	static final public ACEPlannerActionListModel ActionList() {
		return acepddl_runner.getDomain().getActionListModel();
	}

	/****************************************************************
	 * Finish Parsing DOMAIN. -->> Start Parsing Problem.....
	 ****************************************************************/
	static final public ACEPlannerProblem parse_problem_pddl() {
		ACEPlannerProblem prob = new ACEPlannerProblem();
		String s;
		s = ProblemName();
		prob.setName(s);
		prob.setDomain(DomainName());

		for (ACEPlannerSnippet snippet : acepddl_runner.getDomain().getGoal().getSnippets()) {
			prob.getGoalState().add(snippet.getAceSnippet());
		}

		for (ACEPlannerSnippet snippet : acepddl_runner.getDomain().getProblem().getSnippets()) {
			prob.getInitState().add(snippet.getAceSnippet());
		}

		return prob;
	}

	/******/
	static final public String ProblemName() {
		return "generic problem name";
	}

}
