package mt.uol.smi.attempto.aceview.planner.model.event;

public enum ModelEventType {
	MODEL_CHANGED,
	ACTION_CHANGED,
	ACTION_REMOVED,
	ACTION_ADDED,
	CONDITION_CHANGED,
	NEW_SNIPPETS_LOADED,
	ACTION_LIST_CHANGED,
	SENTENCES_USED_SNIPPETS_LOADED,
	MODEL_LOADED;
}